In [0]:
# Creating single col df with List of tuples
roll_num_list=[(10,), (20,)]
print(type(roll_num_list))
print(type(roll_num_list[1]))

<class 'list'>
<class 'tuple'>

In [0]:
# COl name=_1, datatype bigint 
spark.createDataFrame(roll_num_list)

Out[7]: DataFrame[_1: bigint]

In [0]:
spark.createDataFrame(roll_num_list, 'age int')

Out[8]: DataFrame[age: int]

In [0]:
# Creating Df using List of Tuples
students_list=[(10, 'Allen'), (20, 'Donlad'), (30, 'Mark')]

# Col Names: _1, _2; Datatypes: bigint, string
spark.createDataFrame(students_list)

Out[10]: DataFrame[_1: bigint, _2: string]

In [0]:
spark.createDataFrame(students_list, 'roll_no int, student_name string')

Out[13]: DataFrame[roll_no: int, student_name: string]